type: match_pairs
visible: false
header: "Match Functions with their Derivatives"
text: |
  And memorize this table.

  This table has to be memorized. By heart. No excuses.
shuffle: true
score: 1
quiz:
  left:
    - text: $\frac{d}{dx}x^k$
    - text: $\frac{d}{dx}\exp(x)$
    - text: $\frac{d}{dx}\sin(x)$
    - text: $\frac{d}{dx}\cos(x)$
    - text: $\frac{d}{dx}\ln x$
    - text: $\frac{d}{dx}\tg x$
    - text: $\frac{d}{dx}\ctg x$
    - text: $\frac{d}{dx}\arcsin x$
    - text: $\frac{d}{dx}\arccos x$
    - text: $\frac{d}{dx}\arctg x$
    - text: $\frac{d}{dx}\arcctg x$
    - text: $\frac{d}{dx}(f(x) + g(x))$
    - text: $\frac{d}{dx}(f(x) g(x))$
    - text: $\frac{d}{dx}(C f(x))$
    - text: $\frac{d}{dx}(f(g(x)))$
  variants:
    - text: $k x^{k-1}$
    - text: $\exp(x)$
    - text: $\cos(x)$
    - text: $-\sin(x)$
    - text: $x^{-1}$
    - text: $\frac{1}{\cos^2 x}$
    - text: $- \frac{1}{\sin^2 x}$
    - text: $\frac{1}{\sqrt{1 - x^2}}$
    - text: $- \frac{1}{\sqrt{1 - x^2}}$
    - text: $\frac{1}{1 + x^2}$
    - text: $- \frac{1}{1 + x^2}$
    - text: $\frac{df(x)}{dx} + \frac{dg(x)}{dx}$
    - text: $\frac{d f(x)}{dx} g(x) + f(x) \frac{dg(x)}{dx}$
    - text: $C \frac{d f(x)}{dx} $
    - text: $\frac{d f}{d g} \frac{d g}{d x}$
